name: build - macos
on:
  workflow_call:
  push:

jobs:
  macos:
    strategy:
      matrix:
        config: [debug, release]
        compiler: [clang]
        arch: [x86]
        include:
          - arch: x86
            os: macos-14
    name: MacOS ${{ matrix.config }} ${{ matrix.compiler }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Installing dependencies
      run: |
        export ICU_ROOT="$(brew --prefix icu4c)" && \
        export PATH="/usr/local/opt/ccache/libexec:/usr/local/opt/gettext/bin:$PATH";
        ./install-dependencies.sh homebrew ccache dylibbundler
    - name: Building
      run: |
        mkdir build_wl
        cd build_wl/
        ../utils/macos/build_app.sh "--${{ matrix.config }}" "--${{ matrix.compiler }}"
        grep -v REVDETECT-BROKEN ../build/VERSION
        DMGPATH="$(pwd)"
        DMGFILE="$(ls *.dmg)"
        echo "DMG file is: $DMGPATH/$DMGFILE"
        mv "$DMGFILE" "${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.config }}-${{ matrix.compiler }}.dmg"

    - name: Uploading DMG
      uses: actions/upload-artifact@v3
      with:
        name: Widelands ${{ matrix.config }} ${{ matrix.compiler }} MacOS 14 ${{ matrix.arch }} AppImage
        path: ${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.config }}-${{ matrix.compiler }}-${{ matrix.arch }}.dmg
